//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Abundance_Nk.Model.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class E_WALLET_PAYMENT
    {
        public long Id { get; set; }
        public long Payment_Id { get; set; }
        public int Fee_Type_Id { get; set; }
        public int Session_Id { get; set; }
        public Nullable<long> Student_Id { get; set; }
        public decimal Amount { get; set; }
        public Nullable<long> Person_Id { get; set; }
    
        public virtual FEE_TYPE FEE_TYPE { get; set; }
        public virtual PAYMENT PAYMENT { get; set; }
        public virtual PERSON PERSON { get; set; }
        public virtual SESSION SESSION { get; set; }
        public virtual STUDENT STUDENT { get; set; }
    }
}
