//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Abundance_Nk.Model.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class LIBRARY_REGISTRATION
    {
        public int Id { get; set; }
        public long Person_Id { get; set; }
        public long User_Id { get; set; }
        public string Guardian_Name { get; set; }
        public string Previous_School_Name { get; set; }
        public Nullable<int> Session_Id { get; set; }
        public System.DateTime Date { get; set; }
    
        public virtual PERSON PERSON { get; set; }
        public virtual SESSION SESSION { get; set; }
        public virtual USER USER { get; set; }
    }
}
