//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Abundance_Nk.Model.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class PROGRAMME_FEE_AMOUNT
    {
        public int Programme_Fee_Amount_Id { get; set; }
        public int Programme_Id { get; set; }
        public int Level_Id { get; set; }
        public int Payment_Mode_Id { get; set; }
        public int Session_Id { get; set; }
        public decimal Amount { get; set; }
    
        public virtual LEVEL LEVEL { get; set; }
        public virtual PAYMENT_MODE PAYMENT_MODE { get; set; }
        public virtual SESSION SESSION { get; set; }
        public virtual PROGRAMME PROGRAMME { get; set; }
    }
}
