//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Abundance_Nk.Model.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class SPILL_OVER_STUDENT
    {
        public long Spillover_Student_Id { get; set; }
        public long Student_Id { get; set; }
        public int Session_Id { get; set; }
        public int Semester_Id { get; set; }
        public long Uploaded_By { get; set; }
    
        public virtual SEMESTER SEMESTER { get; set; }
        public virtual SESSION SESSION { get; set; }
        public virtual STUDENT STUDENT { get; set; }
        public virtual USER USER { get; set; }
    }
}
