//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Abundance_Nk.Model.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class STUDENT_MATRIC_NUMBER_GENERATION_AUDIT
    {
        public long Id { get; set; }
        public string Starting_Matric_Number { get; set; }
        public string Ending_Matric_Number { get; set; }
        public string Prefix { get; set; }
        public string Suffix { get; set; }
        public Nullable<int> Start_Number { get; set; }
        public Nullable<int> Number_Length { get; set; }
        public Nullable<int> Programme_Id { get; set; }
        public Nullable<int> Department_Id { get; set; }
        public Nullable<int> Session_Id { get; set; }
        public long User_Id { get; set; }
        public string Operation { get; set; }
        public string Action { get; set; }
        public System.DateTime Time { get; set; }
        public string Client { get; set; }
    
        public virtual DEPARTMENT DEPARTMENT { get; set; }
        public virtual SESSION SESSION { get; set; }
        public virtual USER USER { get; set; }
        public virtual PROGRAMME PROGRAMME { get; set; }
    }
}
