//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Abundance_Nk.Model.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class TERTIARY_INSTITUTION
    {
        public TERTIARY_INSTITUTION()
        {
            this.APPLICANT_PREVIOUS_EDUCATION = new HashSet<APPLICANT_PREVIOUS_EDUCATION>();
            this.APPLICANT_SECOND_PREVIOUS_EDUCATION = new HashSet<APPLICANT_SECOND_PREVIOUS_EDUCATION>();
        }
    
        public int Tertiary_Institution_Id { get; set; }
        public string Name { get; set; }
        public string Description { get; set; }
        public bool Activated { get; set; }
    
        public virtual ICollection<APPLICANT_PREVIOUS_EDUCATION> APPLICANT_PREVIOUS_EDUCATION { get; set; }
        public virtual ICollection<APPLICANT_SECOND_PREVIOUS_EDUCATION> APPLICANT_SECOND_PREVIOUS_EDUCATION { get; set; }
    }
}
