//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Abundance_Nk.Model.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class VW_COMPREHENSIVE_SCHOOL_FEES_PAYMENT_REPORT
    {
        public string Name { get; set; }
        public long Person_Id { get; set; }
        public string Programme_Name { get; set; }
        public int Programme_Id { get; set; }
        public string Programme_Short_Name { get; set; }
        public string Programme_Description { get; set; }
        public string Department_Code { get; set; }
        public int Department_Id { get; set; }
        public string Department_Name { get; set; }
        public int Session_Id { get; set; }
        public string Session_Name { get; set; }
        public string RRR { get; set; }
        public string Description { get; set; }
        public string Status { get; set; }
        public string Customer_Name { get; set; }
        public int Fee_Type_Id { get; set; }
        public string Invoice_Number { get; set; }
        public long Payment_Id { get; set; }
        public string Contact_Address { get; set; }
        public Nullable<System.DateTime> Date_Of_Birth { get; set; }
        public string Email { get; set; }
        public string Image_File_Url { get; set; }
        public string Signature_File_Url { get; set; }
        public string Mobile_Phone { get; set; }
        public Nullable<decimal> Amount { get; set; }
        public Nullable<int> Ewallet_FeeType_Id { get; set; }
        public string Ewallet_Feetyp_Name { get; set; }
        public string Payment_Feetyp_Name { get; set; }
        public int Payment_Feetype_Name { get; set; }
        public decimal Transaction_Amount { get; set; }
        public System.DateTime Transaction_Date { get; set; }
        public int Level_Id { get; set; }
        public string Level_Name { get; set; }
        public string Matric_Number { get; set; }
    }
}
