//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Abundance_Nk.Model.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class VW_STUDENT_INFORMATION
    {
        public long Person_Id { get; set; }
        public string Name { get; set; }
        public string Contact_Address { get; set; }
        public System.DateTime Date_Entered { get; set; }
        public Nullable<System.DateTime> Date_Of_Birth { get; set; }
        public string Email { get; set; }
        public string Home_Address { get; set; }
        public string Home_Town { get; set; }
        public string Image_File_Url { get; set; }
        public string Mobile_Phone { get; set; }
        public string Title { get; set; }
        public Nullable<bool> Activated { get; set; }
        public string Matric_Number { get; set; }
        public string Reason { get; set; }
        public string School_Contact_Address { get; set; }
        public int Programme_Id { get; set; }
        public string Programme_Name { get; set; }
        public int Department_Id { get; set; }
        public string Department_Name { get; set; }
        public int Level_Id { get; set; }
        public string Level_Name { get; set; }
        public int Session_Id { get; set; }
        public string Session_Name { get; set; }
        public Nullable<int> Department_Option_Id { get; set; }
        public string Department_Option_Name { get; set; }
        public int Student_Status_Id { get; set; }
        public string Student_Status_Name { get; set; }
        public Nullable<byte> Sex_Id { get; set; }
        public string Sex_Name { get; set; }
        public string State_Id { get; set; }
        public string State_Name { get; set; }
        public Nullable<int> Local_Government_Id { get; set; }
        public string Local_Government_Name { get; set; }
        public Nullable<int> Nationality_Id { get; set; }
        public string Nationality_Name { get; set; }
        public Nullable<System.DateTime> Graduation_Date { get; set; }
        public Nullable<int> Year_Of_Admission { get; set; }
        public Nullable<int> Year_Of_Graduation { get; set; }
        public Nullable<int> Mode_Of_Entry_Id { get; set; }
        public string Mode_Of_Entry_Name { get; set; }
        public Nullable<int> Mode_Of_Study_Id { get; set; }
        public string Mode_Of_Study_Name { get; set; }
        public string Application_Exam_Number { get; set; }
        public string Application_Form_Number { get; set; }
        public Nullable<int> Admitted_Department_Id { get; set; }
        public Nullable<int> Admitted_Option_Id { get; set; }
        public Nullable<int> Admitted_Programme_Id { get; set; }
        public Nullable<int> Admitted_Session_Id { get; set; }
        public string Applicant_Jamb_Registration_Number { get; set; }
        public Nullable<short> Applicant_Jamb_Score { get; set; }
    }
}
